json.id event.id
json.name event.name
json.image_url event.image_url
json.description event.description
json.date event.date
json.time event.time
json.location event.location
json.created_at event.created_at
json.updated_at event.updated_at
